branches:
  only:
    - master
language: node_js
cache: npm
script:
  - npm run lint
  - npm test
  - npx codecov
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_DEPLOY_ACCESS_KEY_ID
  secret_access_key: $AWS_DEPLOY_SECRET_ACCESS_KEY
  region: $AWS_DEPLOY_REGION
  app: "0x Tracker Worker"
  env: $AWS_DEPLOY_ENV
  bucket_name: $AWS_DEPLOY_BUCKET_NAME
  wait_until_deployed: true
  on:
    branch: master
