branches:
  only:
    - master
language: node_js
cache: npm
script:
  - npm run lint
  - npm test
  - npx codecov
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_DEPLOY_ACCESS_KEY_ID
  secret_access_key: $AWS_DEPLOY_SECRET_ACCESS_KEY
  region: $AWS_DEPLOY_REGION
  app: $AWS_DEPLOY_APP_NAME
  env: $AWS_DEPLOY_ENV
  bucket: $AWS_DEPLOY_BUCKET_NAME
  edge: true
  cleanup: false
  on:
    branch: master
